language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
env:
  JDK6_BOOT_CLASSPATH: /usr/lib/jvm/java-6-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/jsse.jar
matrix:
  include:
    - name: "JDK 8, Python 3.6"
      jdk: "openjdk8"
      env: TEST_SUITE=java8
    #- name: "JDK 7, Python 2.7"
      #jdk: "openjdk7"
      #env: TEST_SUITE=java7
    - name: "JDK 6, Python 2.7"
      jdk: "openjdk6"
      env: TEST_SUITE=java6
      before_install:
        - wget -O ~/gradle.bin.zip 'https://services.gradle.org/distributions/gradle-2.14.1-bin.zip'
        - unzip ~/gradle.bin.zip -d ~/gradle
        - ls -l ~/
        - ls -l ~/gradle/gradle-2.14.1
        - export PATH="~/gradle/gradle-2.14.1/bin:$PATH"
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/pip
    - $HOME/.pyenv/
install:
  - eval "$(pyenv init -)"
  - if [ $TEST_SUITE == "java8" ] ; then pyenv install 3.6.6; pyenv global 3.6.6; pip install --user flake8==2.5.0; fi
  - if [ $TEST_SUITE == "java7" ] ; then pyenv install 2.7.12; pyenv global 2.7.12; fi
  - if [ $TEST_SUITE == "java6" ] ; then pyenv install 2.7.12; pyenv global 2.7.12; fi
  - cd py4j-java
  - gradle --version
  - gradle clean
  - pip install --user nose
  - echo "$PATH" && echo `java -version` && echo `javac -version` && echo `python --version` && echo $JAVA_HOME
before_script:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
script:
  - gradle check
  - gradle assemble
  - cd ../py4j-python
  - if [ $TEST_SUITE == "java8" ] ; then flake8; fi
  - nosetests -v
