language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk
env:
  matrix:
  include:
    - name: "JDK 8, Python 3.6"
      jdk: "openjdk8"
      env: TEST_SUITE=java8
    - name: "JDK 7, Python 2.7"
      jdk: "openjdk7"
      env: TEST_SUITE=java7
    # Left in case someone wants to try to build with JDK 6, which uses an old
    # TLS version no longer supported by Maven Central. Maven Central is
    # required to build and test Py4J (junit).
    #- name: "JDK 6, Python 2.7"
      #jdk: "openjdk6"
      #env: TEST_SUITE=java6
      #before_install:
        #- wget -O ~/gradle.bin.zip 'https://services.gradle.org/distributions/gradle-2.14.1-bin.zip'
        #- unzip ~/gradle.bin.zip -d ~/gradle
        #- ls -l ~/
        #- ls -l ~/gradle/gradle-2.14.1
        #- export PATH="~/gradle/gradle-2.14.1/bin:$PATH"
before_cache:
  # Recommended by Travis CI doc
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.cache/pip
install:
  - eval "$(pyenv init -)"
  - if [ $TEST_SUITE == "java8" ] ; then pyenv global 3.6.3; pip install --user flake8==2.5.0; fi
  - if [ $TEST_SUITE == "java7" ] ; then pyenv install 2.7.12; pyenv global 2.7.12; fi
  # Left in case someone wants to try to build with JDK 6.
  #- if [ $TEST_SUITE == "java6" ] ; then pyenv install 2.7.12; pyenv global 2.7.12; fi
  - pip install --user nose
  - cd py4j-java
  - gradle clean
  # Useful in case the build stops working because of version issues.
  - gradle --version
  - echo `java -version` && echo `javac -version` && echo `python --version`
  - echo $PATH
  - echo $JAVA_HOME
before_script:
  # Enable IPv6
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
script:
  # Our gradle build file will take this env variable and set the bootstrap
  # class path to JDK 6 because source compatibility is set to 6.
  - export JDK6_BOOT_CLASSPATH=/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-6-openjdk-amd64/jre/lib/jsse.jar
  - gradle check
  - gradle assemble
  - cd ../py4j-python
  # Only run flake8 once to save time.
  - if [ $TEST_SUITE == "java8" ] ; then flake8; fi
  - nosetests -v
